// DEPRECATED: This script is no longer needed
// Summaries are now automatically generated by ElevenLabs via post-call webhooks
// 
// This file is kept for reference only and should not be used.
// 
// For information about the new webhook-based summary system, see:
// - server/webhooks/elevenlabs-webhooks.ts
// - Documentation on ElevenLabs post-call webhooks

import { storage } from './storage';

async function checkSummaryStatus() {
  try {
    console.log('⚠️  DEPRECATED: Batch summary generation is no longer available');
    console.log('ℹ️  Summaries are now automatically generated by ElevenLabs via webhooks\n');
    
    // Get admin user for testing
    const adminUser = await storage.getUserByEmail('cc@siwaht.com');
    if (!adminUser) {
      console.error('Admin user not found');
      return;
    }

    console.log('[SUMMARY-STATUS] Checking summary status for organization:', adminUser.organizationId);
    
    // Get all call logs for the organization
    const allCallLogs = await storage.getCallLogs(adminUser.organizationId);
    
    // Extract data from paginated response
    const callLogsData = allCallLogs.data || allCallLogs;
    
    // Count calls with and without summaries
    const callsWithSummary = callLogsData.filter((log: any) => log.summary).length;
    const callsWithoutSummary = callLogsData.filter((log: any) => log.transcript && !log.summary).length;
    const totalCalls = callLogsData.length;
    
    console.log('\n================================');
    console.log('[SUMMARY-STATUS] Summary Statistics:');
    console.log(`📊 Total Calls: ${totalCalls}`);
    console.log(`✅ Calls with Summary: ${callsWithSummary}`);
    console.log(`❌ Calls without Summary: ${callsWithoutSummary}`);
    console.log('================================\n');
    
    console.log('ℹ️  New calls will automatically receive summaries via ElevenLabs webhooks');
    console.log('ℹ️  Existing calls without summaries cannot be retroactively summarized');
    console.log('ℹ️  Ensure your agents have post-call webhooks configured in ElevenLabs\n');
    
    // Exit successfully
    process.exit(0);
  } catch (error: any) {
    console.error('[SUMMARY-STATUS] Error:', error.message);
    process.exit(1);
  }
}

// Run the summary status check
checkSummaryStatus();
